language: generic

os: linux
dist: xenial

jobs:
  include:
    - dist: trusty
      env: THIS_OS=trusty
    - dist: xenial
      env: THIS_OS=xenial
    - dist: bionic
      env: THIS_OS=bionic

branches:
  except:
    - gh-pages

git:
  depth: 9999

env:
  global:
    - INSTALLDIR="$HOME/taucmdr-test"
    - __TAUCMDR_PROGRESS_BARS__="disabled"

before_install:
  - git --version
  - mount
  - gcc --version

# Test `make install` while boostraping Python 2.7 environment and required packages.
install:
  - make install INSTALLDIR="$INSTALLDIR" || (tail -1000 "$HOME/.local/taucmdr/debug_log" && false)
  - export PATH="$INSTALLDIR/conda/bin:$PATH"
  - which python
  - which pip
  - pip install --prefix "$INSTALLDIR/conda" -r requirements-dev.txt

# Use travis_wait to extend the expected runtime of the command.
script:
  - travis_wait 30 coverage run setup.py test

after_failure:
  - tail -1000 "$HOME/.local/taucmdr/debug_log"

after_script:
  - codecov --env THIS_OS

notifications:
  email:
    recipients:
      - taucmdr-notify@paratools.com
    on_success: change  # options: [always|never|change]
    on_failure: change
