language: python

branches:
  except:
    - gh-pages

git:
  depth: 9999

sudo: false
os:
  - linux

env:
  global:
    - INSTALLDIR="$HOME/taucmdr-test"
  matrix:
    - OS='Ubuntu Precise' # Add more python versions to this array to expand test matrix

# Boostrap Python 2.7 environment and required packages.
install:
  - make python_check INSTALLDIR="$INSTALLDIR"
  - source "$INSTALLDIR/conda/bin/activate"
  - pip install --prefix "$INSTALLDIR/conda" -r requirements.txt

script:
  - coverage run ./configure --prefix="$INSTALLDIR"
  - make install PYTHON_EXE="coverage run"
  - coverage run setup.py test

after_success:
  - codecov --env OS

deploy:
  provider: script
  script: python setup.py build_sphinx \
              --update-gh-pages \
              --gh-origin-url "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" \
              --gh-user-name "Travis-CI-bot" \
              --gh-user-email "info@paratools.com" \
              --gh-commit-msg "Updated documentation on Travis-CI job $TRAVIS_JOB_NUMBER at commit $TRAVIS_COMMIT"
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
    repo: ParaToolsInc/taucmdr # Don't try to deploy on private forks

notifications:
  email:
    recipients:
      - taucmdr-notify@paratools.com
    on_success: always  # options: [always|never|change]
    on_failure: always
    on_start: always
  webhooks:
    urls: # gitter.im announcement
      secure: TQIzGX9yWDc+ayKNpWmNjCCucaGCwt9CYeThbzdmGsA30hJkRRuDNdx5ZDvknRktV+h+QYgLGLR3ueVUuGL0/kf23vPUZD6kTTY0c3ZJ4fonDx5Ydr+zhc1iJzO/Ord1tnY5xxfvKpfWEUekFQT5SSJMt61CQoNmVSDdTDpFcMC4GEzeQD6fdP0BxgiFvw4UOnfU/poM9OmjaVdKoFyax1+gub4mC/GG9faxK6IdtOAtPsGcUOpzBypwj3NRGgDuq+jErnvm3tLitVJz8h1ab5eQMgTAlCK8q3w7x/WaWxsVXnErjDqJIGs9mpxmyOJERoRv7hQdlAZtKlIZsdGpE7O9B9ooBE/zAfRqGHee5CsA/UKx6XDt9h0rYt/zNJ5RcIrbHRZMilwdC4PXXjN7FNNkpDp0LhhpzM19tZx9+Zb/QAGOTwIDq5adQfiF9ctE7OAlvqnSbvhTL0bzLmYthIURc9nBks4uqUAKq/LEnHz2CgiL8fGaJbUXqGSBc/prKYREa9ckfBdjFfngSnLBJB6oLKQBGRA/Y8thi7etu8TZD9CsWcBJhXFJTPkFArFkJVRpURNpQ0OIS54q0bmTW+dPbSJ95v2GEttCuAIyqDgffuwqqVYx0KmaMHKvxUGx0Mu8uC9Mo5FLEDiM05mE/lAgkK9wgwbgFW+A5g2t7x8=
    on_success: always  # options: [always|never|change]
    on_failure: always
    on_start: always

